global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 애플리케이션 메트릭
  - job_name: 'agentic-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis 메트릭 (Redis Exporter 필요)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL 메트릭 (Postgres Exporter 필요)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

# 알림 규칙
rule_files:
  - 'alerts.yml'

# Alertmanager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Alertmanager 주소